apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 28.3.1
# renovate: image=traefik
appVersion: v3.0.3
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix: 🐛 namespaced rbac when kubernetesIngress provider is disabled"
    - "fix: 🐛  add divisor: '1' to GOMAXPROCS and GOMEMLIMIT"
    - "fix(security): 🐛 🔒️ mount service account token on pod level"
    - "fix(Traefik Hub): remove obsolete CRD"
    - "fix(Traefik Hub): remove namespace in mutating webhook"
    - "feat: allow setting permanent on redirectTo"
    - "chore(release): publish v28.3.0"
    - "chore(deps): update traefik docker tag to v3.0.2"
