name: Release Charts

on:
  push:
    branches:
      - master

env:
  tag_prefix: v

jobs:
  test:
    uses: "traefik/traefik-helm-chart/.github/workflows/test.yml@master"
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global --add safe.directory /charts

      - name: Copy LICENSE and README.md for packaging
        run: |
          cp ./README.md ./traefik/README.md
          cp ./EXAMPLES.md ./traefik/EXAMPLES.md
          cp ./LICENSE ./traefik/LICENSE

      - name: Generate default static install
        run: |
          kustomize build traefik/crds > traefik.yaml
          helm template traefik ./traefik -n traefik >> traefik.yaml

      - name: Get chart verison
        id: chart_version
        run: |
          echo "CHART_VERSION=$(cat traefik/Chart.yaml | awk -F"[ ',]+" '/version:/{print $2}')" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: tag_exists
        run: |
          TAG_EXISTS=true
          if ! [ $(git tag -l "${{ env.tag_prefix }}${{ steps.chart_version.outputs.CHART_VERSION }}") ]; then
              TAG_EXISTS=false
          fi
          echo TAG_EXISTS=$TAG_EXISTS >> $GITHUB_OUTPUT

      - name: Tag release
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.chart_version.outputs.CHART_VERSION }}
          tag_prefix: ${{ env.tag_prefix }}
        if: steps.tag_exists.outputs.TAG_EXISTS == 'false'

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          prerelease: ${{ contains(steps.chart_version.outputs.CHART_VERSION, '-') }}
          artifacts: "traefik.yaml"
        if: steps.tag_exists.outputs.TAG_EXISTS == 'false'

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.CHARTS_TOKEN }}
          charts_dir: .
          charts_url: https://traefik.github.io/charts
          owner: traefik
          repository: charts
          branch: master
          target_dir: traefik
          index_dir: .
          commit_username: traefiker
          commit_email: 30906710+traefiker@users.noreply.github.com
        if: steps.tag_exists.outputs.TAG_EXISTS == 'false'

      - name: Publish Helm chart to the OCI registry
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: traefik
          repository:  ${{ secrets.REGISTRY_USERNAME }}
          tag: ${{ steps.chart_version.outputs.CHART_VERSION }}
          path: ./traefik # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
          update_dependencies: 'true' # Defaults to false
        if: steps.tag_exists.outputs.TAG_EXISTS == 'false'
        # helm pull ghcr.io/appany/my-chart:0.1.0
